### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Ramacap** [ffreemt/google-itranslate#1]
Hi!

English word "organic" is giving me that error, if i use "organic ok" it work fine

![image](https://user-images.githubusercontent.com/76523352/132012190-70236f21-25ea-4642-ac08-d40b4f97c43a.png)

other words work just fine!

any clue?

thanks in advanced!

**Comment by ffreemt** [comment]
Thanks for reporting the issue.

I did a quick fix in the repo but have yet to update pypi. It will likely take some time to update pypi since the package name will have to be changed.

In the meantime, you may try to install it directly from the repo, e.g.,
```bash
pip install  git+https://github.com/ffreemt/google-stranslate
```
Note the `s` in `stranslate`.

Please let me know should there be other issues.

Thanks.

**Comment by jumorap** [comment]
Hello, I have the same issue. I installed it through git+https://github.com/ffreemt/google-stranslate, but it didn't fix the trouble
![image](https://user-images.githubusercontent.com/57921215/155083629-289807fa-581a-4107-841c-3d2176b40a92.png)

![image_2022-02-22_023020](https://user-images.githubusercontent.com/57921215/155083520-624a37bb-f780-4487-bba9-5dcaf9884e5b.png)

It works once, but after it, stops working.
Thanks!
